In [ ]:
import numpy as np

np.__version__

'2.0.2'

1. Створити матрицю 3х3 і заповнити її випадковими числами від 1 до 5

In [ ]:
matrix = np.random.randint(1, 6, size=(3, 3))
matrix

array([[5, 4, 2],
       [2, 5, 4],
       [3, 1, 1]])

2. Обчислити визначник матриці

In [ ]:
det = np.linalg.det(matrix)
det

np.float64(19.000000000000004)

3. Знайти добуток всіх елементів матриці

In [ ]:
product = np.prod(matrix)
product

np.int64(4800)

In [ ]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1 * prod_2 * prod_3

np.int64(4800)

4. Знайти суму всіх елементів в матриці

In [ ]:
sum = np.sum(matrix)
sum

np.int64(27)

5. Обчислити найбільший, найменший елементи

In [ ]:
max_element = np.max(matrix)
min_element = np.min(matrix)

print(f"Найбільший елемент матриці {max_element}")
print(f"Найменший елемент матриці {min_element}")

Найбільший елемент матриці 5
Найменший елемент матриці 1


6. Знайти середніє значення елементів матриці

In [ ]:
mean = np.mean(matrix)
mean

np.float64(3.0)

7. Знайти матрицю, що складена з квадратних коренів

In [ ]:
sqrt_matrix = np.sqrt(matrix)
sqrt_matrix

array([[2.23606798, 2.        , 1.41421356],
       [1.41421356, 2.23606798, 2.        ],
       [1.73205081, 1.        , 1.        ]])

8. Обчислити суму елементів кожного рядка. Відповідь записати як вектор-стовпчик

In [ ]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)
print(f"Сума елементів кожного рядка\n{row_sums}")

Сума елементів кожного рядка
[[11]
 [11]
 [ 5]]


9. Створити вектор, що містить 25 елементів. Заповнити від 0 до 9. Відсортувати за спаданням

In [ ]:
vector = np.random.randint(0, 10, size = 25)

print(f"Початковий вектор:\n{vector}")

# Сортуємо числа за спаданням
sorted_vector = np.sort(vector)[::-1]

print(f"Вектор після сортування:\n{sorted_vector}")


Початковий вектор:
[8 3 7 5 5 9 9 3 7 9 8 9 6 2 9 3 0 0 9 7 5 0 6 8 5]
Вектор після сортування:
[9 9 9 9 9 9 8 8 8 7 7 7 6 6 5 5 5 5 3 3 3 2 0 0 0]


10. Знайти моду, медіану, середнє, максимальне, мінімальне значення

In [ ]:
from scipy import stats

#Знаходимо моду
mode = stats.mode(vector)

#Знаходимо медіану
median = np.median(vector)

#Знаходимо середнє
mean = np.mean(vector)

#Знаходимо максимальне значення
max_value = np.max(vector)

#Знаходимо мінімальне значення
min_value = np.min(vector)

#Виводимо значення
print(f"{mode}\n{median}\n{mean}\n{max_value}\n{min_value}")

ModeResult(mode=np.int64(9), count=np.int64(6))
6.0
5.68
9
0


11. Створити дві матриці 4х4, заповнені числави від 1 до 10. Обчислити суму, різницю, поелеметний добуток, частку

In [ ]:
matrix_1 = np.random.randint(1, 11, size = (4, 4))
matrix_2 = np.random.randint(1, 11, size = (4, 4))

print(f"Матриця 1:\n{matrix_1}\nМатриця 2:\n{matrix_2}")

matrix_sum = matrix_1 + matrix_2
print(f"Сума\n{matrix_sum}")

matrix_diff = matrix_1 - matrix_2
print(f"Різниця\n{matrix_diff}")

matrix_prod = matrix_1 * matrix_2
print(f"Добуток\n{matrix_prod}")

matrix_division = np.divide(matrix_1, matrix_2)
print(f"Частка\n{matrix_division}")

Матриця 1:
[[ 7  1  8  5]
 [ 1  2  6 10]
 [ 5  2  9  1]
 [ 8  4  1  2]]
Матриця 2:
[[7 6 7 8]
 [7 7 5 9]
 [3 2 7 6]
 [5 4 2 8]]
Сума
[[14  7 15 13]
 [ 8  9 11 19]
 [ 8  4 16  7]
 [13  8  3 10]]
Різниця
[[ 0 -5  1 -3]
 [-6 -5  1  1]
 [ 2  0  2 -5]
 [ 3  0 -1 -6]]
Добуток
[[49  6 56 40]
 [ 7 14 30 90]
 [15  4 63  6]
 [40 16  2 16]]
Частка
[[1.         0.16666667 1.14285714 0.625     ]
 [0.14285714 0.28571429 1.2        1.11111111]
 [1.66666667 1.         1.28571429 0.16666667]
 [1.6        1.         0.5        0.25      ]]


Висновок: в результаті виконання лабораторної роботи я розвинув навички роботи з бібліотекою numpy мови програмування Python