In [2]:
import numpy as np

1. Задати вектор, що складається з перших п'яти натуральних чисел.

In [3]:
vector = np.array([1,2,3,4,5])
vector


array([1, 2, 3, 4, 5])

2. Транспортувати вектор

In [4]:
v1 = np.matrix([1,2,3,4,5])
print(v1)
v2 = v1.T
v2

[[1 2 3 4 5]]


matrix([[1],
        [2],
        [3],
        [4],
        [5]])

3. Напишіть функцію, яка перевертає вектор у зворотньому порядку

In [5]:
v = np.array([1,2,3,4,5])
print(v[::-1])

[5 4 3 2 1]


In [6]:
v = np.flip(v)
print(v)

[5 4 3 2 1]


4. Обчислити середнє значення вектора

In [7]:
print(np.mean(v))

3.0


5. Знайти найбільший і найменший елементи вектора

In [8]:
print(np.max(v))
print(np.min(v))

5
1


6. Обчислити скалярний добуток (dot product) двох векторів

In [9]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

print(np.dot(v1,v2))
print(v1*v2)

32
[ 4 10 18]


7. Напишіть функцію яка нормалізує вектор (зводить до одиничної довжини).

In [10]:
v = np.array([1,2,3,4,5])
norm = np.linalg.norm(v)

print(norm)

v/norm

7.416198487095663


array([0.13483997, 0.26967994, 0.40451992, 0.53935989, 0.67419986])

8. Задайте два вектори. Визначте, чи є вони ортогональними. Підказка: якщо скалярний добуток дорівнює нулю - вектори ортогональні.

In [11]:
v1 = np.array([1,0,0])
v2 = np.array([0,1,0])

np.dot(v1,v2)

np.int64(0)

9. Визначити унікальні елементи вектора

In [12]:
v = np.array([1,2,3,2,4,5,3])
np.unique(v)

array([1, 2, 3, 4, 5])

10. Знайти вектори

In [13]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

print(v1 - v2)
print(v2 - v1)
print(v1 + v2)
print(v2 + v1)
print(v1 * v2)
print(v2 * v1)
print(v1 / v2)
print(v2 / v1)

[-3 -3 -3]
[3 3 3]
[5 7 9]
[5 7 9]
[ 4 10 18]
[ 4 10 18]
[0.25 0.4  0.5 ]
[4.  2.5 2. ]


11. Перевірити, чи дорівнює довжина вектора 5

In [14]:
vector = np.array([1,2,3,4,5])
length = np.linalg.norm(vector)

np.isclose(length, 5)

np.False_

12. Задати матрицю, заповнену випадковими числами

In [15]:
a = np.random.randint(0,11,(3,3))
a

array([[ 2, 10,  9],
       [ 4,  9, 10],
       [ 4,  5,  4]])

13. Обчислити визначник матриці

In [16]:
np.linalg.det(a)

np.float64(68.00000000000001)

14. Знаходження оберненої матриці

In [17]:
np.linalg.inv(a)

array([[-0.20588235,  0.07352941,  0.27941176],
       [ 0.35294118, -0.41176471,  0.23529412],
       [-0.23529412,  0.44117647, -0.32352941]])

15. Розв'яжіть систему лінійних рівнянь A*x=b, де A - матриця коефіцієнтів, b - вектор вільних членів.

In [18]:
a = np.array([[1,3,-4], [0,2,-3], [-2,2,5]])
b = np.array([5,3,4])

x = np.linalg.solve(a,b)
print(x)

inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print(x1)

[0.38888889 1.83333333 0.22222222]
[0.38888889 1.83333333 0.22222222]


In [19]:
16. Множення двох матриць

SyntaxError: invalid syntax (ipython-input-1722892339.py, line 1)

In [ ]:
a = np.array([[1,3,-4], [0,2,-3], [-2,2,5]])
b = np.array([5,3,4])

np.dot(a,b)

In [ ]:
a = np.matrix([[1,3,-4], [0,2,-3]])
b = np.matrix([[5,3,4], [2,3,5], [3,2,3]])
print(a)
print(b)
print(np.dot(a,b))

17. Транспонування матриці

In [ ]:
print(a.T)
print(b.T)

In [ ]:
print(np.transpose(a))
print(np.transpose(b))

18. Перевірка симетричності матриці

In [ ]:
matrix = np.matrix([[2,2,2], [2,2,2], [2,2,2]])

np.allclose(matrix, matrix.T)

19. Обчислення сліду матриці

In [ ]:
np.trace(matrix)

20. Дії з матрицями

In [ ]:
a = np.matrix([[1,2], [3,4]])
b = np.matrix([[5,6], [7,8]])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

21. Піднесення матриці до ступеня

In [ ]:
a = np.matrix([[1,2], [3,4]])

np.linalg.matrix_power(a,2)

22. Сортування рядків або стовпців матриці

In [ ]:
b = np.matrix([[5,3,4], [2,3,5], [3,2,3]])

print(b)
print(np.sort(b, axis=0))
print(np.sort(b, axis=1))
print(np.sort(b, axis= None))

In [20]:
a = np.array([[1,4], [3,1]])

print(a)
print(np.sort(a))

[[1 4]
 [3 1]]
[[1 4]
 [1 3]]


23. Підрахувати суму елементів кожного рядка матриці. Відповідь запиши, як вектор стовпчик.

In [21]:
row_sums = np.sum(a, axis=1).reshape(-1,1)

print(f"Сума елементів кожного рядка:\n{row_sums}")

# В результаті отримали вектор - стовпчик

Сума елементів кожного рядка:
[[5]
 [4]]


Висновок: в ході виконання лабораторної роботи було закріплено навички роботи з масивами, векторами та матрицями, застосування базових лінійних та статистичних операцій за допомогою засобів бібліотеки NumPy мови програмування Python.